### ISSUE TITLE
Create 404 page⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

### ISSUE THREAD

**Issue by BeeCeeTee** [thomas-forte/TimeCapsule#12]
Create a 404 page with a spiral of clocks on a white background and a randomly selected time-related quote in the center.

**Comment by thomas-forte** [comment]
No longer needed
