### ISSUE TITLE
Default date⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

### ISSUE THREAD

**Issue by BeeCeeTee** [thomas-forte/TimeCapsule#19]
Default to a random year of the current day and month when the page loads or reloads

**Comment by thomas-forte** [comment]
Using a list of initial dates using some fun ones from history and fiction.
