### ISSUE TITLE
Remove dates⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

### ISSUE THREAD

**Issue by BeeCeeTee** [thomas-forte/TimeCapsule#21]
Remove pre-01/01/1950 dates from the date picker on mobile (still shows up for some reason)

**Comment by thomas-forte** [comment]
I believe this will need to be mitigated by picking a library element over using the native input[type="date"] field

**Comment by thomas-forte** [comment]
No longer an issue with the new date picker
