### ISSUE TITLE
Error page font color⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

### ISSUE THREAD

**Issue by BeeCeeTee** [thomas-forte/TimeCapsule#24]
Change quote font color on error page to a darker color to contrast with the background more clearly and be more readable

**Comment by thomas-forte** [comment]
The app is now a true SPA and there is no navigation so no error page is needed
