### ISSUE TITLE
Go Button Color Change⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

### ISSUE THREAD

**Issue by BeeCeeTee** [thomas-forte/TimeCapsule#33]
Make the "go" arrow button change from dark grey #1E1E1E to light blue #8BF8FF when a date has been selected

**Comment by thomas-forte** [comment]
I believe this doesn't make sense anymore since a date is always selected.
